### ISSUE TITLE
package.json points to index.js, not src/index.js

### ISSUE THREAD

**Issue by mark-hahn** [thefourtheye/deep-inspect#2]
package.json points to index.js, not src/index.js, so the node module loader fails.

**Comment by thefourtheye** [comment]
Ah, that's terrible. Very sorry. Thanks for pointing out. Fix has been landed in https://github.com/thefourtheye/deep-inspect/commit/3326b93d06b92bebe68e27dfef333ed5b6fdbb6d

**Comment by thefourtheye** [comment]
I published v0.0.2 with this fix. PTAL. Thanks once again.
